### ISSUE TITLE
Server crashing on line 124 of controller.js (setReminderStatusToClosed)

### ISSUE THREAD

**Issue by james-carlson** [maintmind/record-management-app#45]
Not sure why, but the server is throwing an error on line 124 of the controller, where we are declaring a variable called reminders to hold the reminder lists coming back from the database.

Edit: if you comment out the variable the error goes away.

**Comment by james-carlson** [comment]
Re-wrote the code to use a different variable name (`reminderList`) instead of `reminders`.

**Comment by james-carlson** [comment]
Still crashing. Error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^


Error: listen EADDRINUSE :::3005
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (/Users/jamescarlson/Desktop/DevMountain/Projects/group/app/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/jamescarlson/Desktop/DevMountain/Projects/group/app/server/server.js:124:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by james-carlson** [comment]
https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server

Stopping node and then using `killall node` before restarting seemed to work.
